@TravelListApp.Api_HostAddress = http://localhost:5147

GET {{TravelListApp.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TravelListApp.Api_HostAddress}}/api/Travel
Accept: application/json
